name: 'Update Fig Autocomplete spec'
description: 'Action to automatically open a new PR to the withfig/autocomplete repo'
author: 'Fig'
inputs:
  token:
    description: 'GitHub access token'
    default: ${{ github.token }}
  autocomplete-spec-name:
    required: true
    description: 'The spec name in the autocomplete repo. Do not include extension and do not include src/ at the beginning'
  spec-path:
    required: true
    description: 'The path to the spec in the actual repo'
  integration:
    description: 'The official Fig integration name used to autogenerate the spec'
  pr-body:
    description: 'The created PR description'
  diff-based-versioning:
    description: 'Use new diff-based versioning'
    default: true
  repo-org:
    description: 'The name of the organization that contains the repo in which to create the PR'
    default: 'withfig'
  repo-name: 
    description: 'The name of the repo in which to create the PR'
    default: 'autocomplete'
runs:
  using: 'node16'
  main: 'dist/index.js'
